# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertimage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import threaded, threading, pytesseract
from PIL import Image

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(612, 464)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/SCD/Python/8bcab946fdf981a1895dd54c3ff055d0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 591, 361))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 571, 331))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 440, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 390, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_select = QtWidgets.QPushButton(Dialog)
        self.btn_select.setGeometry(QtCore.QRect(300, 380, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.btn_select.setFont(font)
        self.btn_select.setObjectName("btn_select")
        self.btn_clear = QtWidgets.QPushButton(Dialog)
        self.btn_clear.setGeometry(QtCore.QRect(400, 380, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_convert = QtWidgets.QPushButton(Dialog)
        self.btn_convert.setGeometry(QtCore.QRect(500, 380, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.btn_convert.setFont(font)
        self.btn_convert.setObjectName("btn_convert")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btn_clear.clicked.connect(self.clear)
        self.btn_select.clicked.connect(self.threading_opendialog)
        self.btn_convert.clicked.connect(self.threading_convert)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chuyển ảnh sang text"))
        self.groupBox.setTitle(_translate("Dialog", "Kết quả"))
        self.label.setText(_translate("Dialog", "Made by Công Danh"))
        self.label_2.setText(_translate("Dialog", "Trạng thái :"))
        self.btn_select.setText(_translate("Dialog", "Chọn ảnh"))
        self.btn_clear.setText(_translate("Dialog", "Xóa"))
        self.btn_convert.setText(_translate("Dialog", "Chuyển text"))

    def clear(self):
        self.plainTextEdit.clear()

    @threaded.Threaded(started=True)
    def convert(self):
        self.label_2.setText("Trạng thái: Đang chuyển")
        pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
        img = Image.open(self.file_name)
        text = pytesseract.image_to_string(img, lang="vie")
        self.plainTextEdit.insertPlainText(text)
        self.label_2.setText("Trạng thái: Đã chuyển xong")

    def threading_convert(self):
        t = threading.Thread(target=self.convert)
        t.start()
        t.join()

    @threaded.Threaded(started=True)
    def opendialog(self):
        file_name,_ = QFileDialog.getOpenFileName()
        #self.file_name = str(file_name)
        print(file_name)
    def threading_opendialog(self):
        t = threading.Thread(target=self.opendialog)
        t.start()
        t.join()
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
